botaccount: 10001
admin-group-num: 5000000
player-group-num: 414410
cooldown: 10
cooldownmsg: "&c你需要等待%cd%秒后才能再次举报!"
title: "&4&l收到新的玩家举报"
subtitle: "&a%reporter% &f-> &c%reported%"
cmd-wake:
  - "梦幻星际"
  - "/mhxj"
  - "小破服人数"
  - ".count"
  - ".c4"
  - "核弹状态"
  - "氢弹状态"
  - "土豆状态"
qq-command-failed: "参数不足. 使用方法: .举报 <目标> <原因>"
game-command-failed: "&c参数不足. 使用方法: /report <目标> <原因>"
playernotOLmessage: "&c玩家不在线 不能举报该玩家"
reportSuccessMessage: "&a感谢你的举报,管理马上到"
reportFormatinQQ: "&f[&7STAFF&f]&a[QQ %reporter%] &f举报了 &c%reported% &f原因: %reason% &7(&f来自: &a%server% &7)"
reportFormatinGame: "&f[&7STAFF&f]玩家&a%reporter% &f举报了 &c%reported% &f原因: %reason% &7(&f来自: &a%server% &7)"
bancmd: "ban %target% 7d 违反服务器规则(不支持解封)"
unbancmd: "unban %target% 管理组成员解封"
mutecmd: "mute %target% 1h 请注意言行"
kickcmd: "kick %target% 注意言行"
enable-widgets: true
muteme: "muteme"
unban: true
plugin-db:
  url: 127.0.0.1:3306
  username: root
  password: 12345
  db: what_db_orwaht
