main: com.kazuha.mireport.main
author: KazuhaAyato
version: 1.4.2-NAA-C
name: MiraiReports
depend: [LiteBans]
description: well
permissions:
  miraireport.report:
    default: true
  miraireport.notify:
    default: op
  miraireport.admin:
    default: op
