main: com.kazuha.mireport.main
author: KazuhaAyato
version: 1.9.1-REV-STABLE-FIX
name: MiraiReports
depend: [LiteBans]
description: well
permissions:
  miraireport.report:
    default: true
  miraireport.notify:
    default: op
  miraireport.admin:
    default: op
